services:
  - type: web
    name: lungcanceranalysis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    runtime: python
    pythonVersion: 3.10.13
